version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0.27
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'nest'
